/*0: {"parser":{"requireEnsure":false}} 

1: {"test":{},"enforce":"pre","use":[{"options":{"cache":true,"formatter":"/home/nikki/Documents/React/test-features/node_modules/react-dev-utils/eslintFormatter.js","eslintPath":"/home/nikki/Documents/React/test-features/node_modules/eslint/lib/api.js","resolvePluginsRelativeTo":"/home/nikki/Documents/React/test-features/node_modules/react-scripts/config","ignore":false,"baseConfig":{"extends":["/home/nikki/Documents/React/test-features/node_modules/eslint-config-react-app/index.js"]},"useEslintrc":false},"loader":"/home/nikki/Documents/React/test-features/node_modules/eslint-loader/dist/cjs.js"}],"include":"/home/nikki/Documents/React/test-features/src"} 

2: {"oneOf":[
  {"test":[{},{},{},{}],"loader":"/home/nikki/Documents/React/test-features/node_modules/url-loader/dist/cjs.js","options":{"limit":10000,"name":"static/media/[name].[hash:8].[ext]"}},
  {"test":{},"include":"/home/nikki/Documents/React/test-features/src","loader":"/home/nikki/Documents/React/test-features/node_modules/babel-loader/lib/index.js","options":{"customize":"/home/nikki/Documents/React/test-features/node_modules/babel-preset-react-app/webpack-overrides.js","babelrc":false,"configFile":false,"presets":["/home/nikki/Documents/React/test-features/node_modules/babel-preset-react-app/index.js"],"cacheIdentifier":"production:babel-plugin-named-asset-import@0.3.4:babel-preset-react-app@9.0.2:react-dev-utils@9.1.0:react-scripts@3.2.0","plugins":[["/home/nikki/Documents/React/test-features/node_modules/babel-plugin-named-asset-import/index.js",{"loaderMap":{"svg":{"ReactComponent":"@svgr/webpack?-svgo,+titleProp,+ref![path]"}}}]],"cacheDirectory":true,"cacheCompression":false,"compact":true}},
  {"test":{},"exclude":{},"loader":"/home/nikki/Documents/React/test-features/node_modules/babel-loader/lib/index.js","options":{"babelrc":false,"configFile":false,"compact":false,"presets":[["/home/nikki/Documents/React/test-features/node_modules/babel-preset-react-app/dependencies.js",{"helpers":true}]],"cacheDirectory":true,"cacheCompression":false,"cacheIdentifier":"production:babel-plugin-named-asset-import@0.3.4:babel-preset-react-app@9.0.2:react-dev-utils@9.1.0:react-scripts@3.2.0","sourceMaps":false}},
  {"test":{},"exclude":{},"use":[{"loader":"/home/nikki/Documents/React/test-features/node_modules/mini-css-extract-plugin/dist/loader.js","options":{}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/css-loader/dist/cjs.js","options":{"importLoaders":1,"sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/postcss-loader/src/index.js","options":{"ident":"postcss","sourceMap":true}}],"sideEffects":true},
  {"test":{},"use":[{"loader":"/home/nikki/Documents/React/test-features/node_modules/mini-css-extract-plugin/dist/loader.js","options":{}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/css-loader/dist/cjs.js","options":{"importLoaders":1,"sourceMap":true,"modules":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/postcss-loader/src/index.js","options":{"ident":"postcss","sourceMap":true}}]},
  {"test":{},"exclude":{},"use":[{"loader":"/home/nikki/Documents/React/test-features/node_modules/mini-css-extract-plugin/dist/loader.js","options":{}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/css-loader/dist/cjs.js","options":{"importLoaders":2,"sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/postcss-loader/src/index.js","options":{"ident":"postcss","sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/resolve-url-loader/index.js","options":{"sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/sass-loader/lib/loader.js","options":{"sourceMap":true}}],"sideEffects":true},
  {"test":{},"use":[{"loader":"/home/nikki/Documents/React/test-features/node_modules/mini-css-extract-plugin/dist/loader.js","options":{}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/css-loader/dist/cjs.js","options":{"importLoaders":2,"sourceMap":true,"modules":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/postcss-loader/src/index.js","options":{"ident":"postcss","sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/resolve-url-loader/index.js","options":{"sourceMap":true}},{"loader":"/home/nikki/Documents/React/test-features/node_modules/sass-loader/lib/loader.js","options":{"sourceMap":true}}]},
  {"loader":"/home/nikki/Documents/React/test-features/node_modules/file-loader/dist/cjs.js","exclude":[{},{},{}],"options":{"name":"static/media/[name].[hash:8].[ext]"}}]} 
*/
